services:
  sotf-server:
    image: sotf-server:latest
    container_name: sotf-server
    build:
      context: container-data
      dockerfile: Containerfile
    restart: unless-stopped
    environment:
      DO_CUSTOM_ACCESSIBILITY_TEST: "false"
      FILTER_SHADER_AND_MESH_AND_WINE_DEBUG: "true"
      FAST_BOOT: "false"
    volumes:
      - "./config:/config"
      - "./data:/data"
    ports:
      - "0.0.0.0:8766:8766/udp"
      - "0.0.0.0:27016:27016/udp"
      - "0.0.0.0:9700:9700/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
