services:
  sotf-server:
    image: sotf-server:redloader
    container_name: sotf-server
    build:
      context: container-data
      dockerfile: Containerfile
    restart: unless-stopped
    environment:
      DO_CUSTOM_ACCESSIBILITY_TEST: "false"
      FILTER_SHADER_AND_MESH_AND_WINE_DEBUG: "true"
      FAST_BOOT: "false"
    volumes:
      - "./config:/config"
      - "./data:/data"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
